services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bo\Bvhs\:
        resource: '../Classes/*'

    B13\Assetcollector\AssetCollector:
        autowire: true
        autoconfigure: true
